### ISSUE TITLE
Using Alfresco 5.1 Community Version

### ISSUE THREAD

**Issue by amet123** [ntmcminn/alfresco-pdf-toolkit#23] opened 2016-03-15 06:15 UTC
Hi

I am Using Afresco 5.1 after install plugin when i open pdf file and apply all options regaing pdf toolkit

Show error "An error occurred when the form was about to be displayed"

Regards

**Comment by mkpelletier** [comment] 2016-03-15 06:36
This is also showing in 5.0d.  Here is the output from the log file:

2016-03-15 08:11:45,701  ERROR [scripts.forms.FormUIGet] [http-apr-8080-exec-10] org.alfresco.repo.forms.FormException: 02150096 Failed to find appropriate FormProcessor to generate Form for item: [pdf-action]pdf-rotate

This error will show up on any PDF action, though obviously the last bit will change relative to the action attempted.

**Comment by ntmcminn** [comment] 2016-03-17 15:52
Hmm.  OK.  I'll check it out.  Something may have changed in Share FormProcessors in 5.x that I missed.

**Comment by ntmcminn** [comment] 2016-03-21 17:55
I can't reproduce this in 5.0.d.  Also not reproducible on 5.1.e with the latest build.  Please give 1.4.0 a try, and let me know if it resolves the problem.

**Comment by amet123** [comment] 2016-03-23 08:05
my discussion based on 1.4.0 i already try this in Community - 5.1.0 (r122274-b3)  @ntmcminn

**Comment by mkpelletier** [comment] 2016-03-23 09:13
My discussion was based on 1.3.1511051607.  I will try with the latest and see if it works.

**Comment by amet123** [comment] 2016-04-17 18:25
@ntmcminn 

after install v 1.4 when i Check in share / module deploy page show v 1.2
![pdf-sign](https://cloud.githubusercontent.com/assets/326649/14589107/d815e494-04f7-11e6-908c-2c408b924d08.jpg)

**Comment by douglascrp** [comment] 2016-04-17 19:02
@amet123 It's safe to use it as it is right now, as those versions are hardcoded inside the extension file, as you can see here https://github.com/ntmcminn/alfresco-pdf-toolkit/blob/master/pdf-toolkit-share/src/main/amp/config/alfresco/web-extension/site-data/extensions/alfresco-pdf-toolkit-extension.xml

@ntmcminn how about using maven variables to fill in those version properties? Maybe using the project.version?

**Comment by amet123** [comment] 2016-04-18 07:08
after Install v 1.4 Alfresco 5.1.e Facing Error  An error occurred when the form was about to be displayed

**Comment by ntmcminn** [comment] 2016-04-19 17:04
Fixing the hard coded versions to use maven props instead, and troubleshooting the form error.

**Comment by ntmcminn** [comment] 2016-04-19 17:28
hard coded versions issue is fixed, but so far I cannot reproduce the "error occurred when form was about to be displayed" issue in my 5.1.e test instance.  Anything in the logs?  If not, could you please raise the log level for package "org.alfresco.repo.forms" to debug and reproduce the error?  This usually happens when something is wrong with the form config, but it all looks to be correct.

**Comment by amet123** [comment] 2016-04-19 19:20
2016-04-20 00:35:51,334 WARN  [org.alfresco.repo.module.ModuleServiceImpl] A previously-installed module 'pdf-toolkit-repo' (version 1.3.1511051607) is not present in your distribution.

Show in alfresco.log

**Comment by ntmcminn** [comment] 2016-04-19 19:52
That's not likely to be related, and that error should go away if both the repository and Share AMPs are properly installed.  You need both for this to work.

**Comment by skcj** [comment] 2016-04-28 11:40
I had the same issue with community 5.1. searched alot....and finally i cleared this by using "-force" command in apply_amps.sh. Before that you need to put pdf-toolkit-repo.amp in /alfresco/amps folder and pdf-toolkit-share.amp in /alfresco/amps_share.

**Comment by ltroud** [comment] 2016-04-29 11:41
tank you very much skcj
same solution for alfresco 5.1e under windows "apply_amps.bat -force" in ms dos prompt

**Comment by skcj** [comment] 2016-05-02 05:15
@ltroud .. nice to hear that it worked for you. Thank you for all the contributors for developing such an  excellent addon.

**Comment by ntmcminn** [comment] 2016-05-05 18:41
Odd that the -force option is required.  Will look into that.  In the meantime, closing this issue.

Thanks all for the help.

**Closed by ntmcminn** 2016-05-05 18:41 UTC
