### ISSUE TITLE
Merge and Append Loses Content Type Meta Data

### ISSUE THREAD

**Issue by mgoodnight27** [ntmcminn/alfresco-pdf-toolkit#8] opened 2014-12-12 20:54 UTC
When performing the above function, a new PDF with standard meta data fields for PDF is created and custom content type information is lost on both PDF's.

**Comment by ntmcminn** [comment] 2015-10-13 16:48
This issue is fixed in commit 6bd40ece4e84a6b401c47a3cfcd25c2a4f711c56, and will be part of 1.3 Beta2.  The issue is with the way that the toolkit was creating new content nodes.  It can either create a brand new node to store the modified document, or it can copy the existing node to preserve content type and metadata.  To change the behavior, use this property:

pdftoolkit.createNew=false

This will tell the tookit to create a copy of the source node, which should preserve metadata, etc.

**Closed by ntmcminn** 2015-10-13 16:48 UTC
